server:
  port: 8889
  servlet:
    encoding:
      enabled: true
      charset: utf-8
      force: true

spring:
  application:
    name: ai-center
  ai:
    dashscope:
      api-key: ${apiKey}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          model: qwen-plus

#